### ISSUE TITLE
Possibility to define settings file in maven2 builder

### ISSUE THREAD

**Issue by cpjolicoeur** [cpjolicoeur/cerberus#3]
We need to use different maven repositories when doing simultanious builds. Therefore I added a possibility to define a maven settings file in the maven2 builder.

Configuration is as follows:

```
builder:
  type: maven2
  maven2:
    task: clean install
    settings: integ_settings.xml
```

The file path for the settings file is relative to the location where the maven2 builder is being run. You may also pass an absolute path if you want to. We have the settings file in scm.

http://cpjolicoeur.lighthouseapp.com/projects/22299/tickets/4-possibility-to-define-settings-file-in-maven2-builder
