### ISSUE TITLE
Possibility to define system properties in maven 2 builder

### ISSUE THREAD

**Issue by cpjolicoeur** [cpjolicoeur/cerberus#4]
In our project we have the need to define system properties for our integration tests which are run with maven. The patch attached makes this possible. The system properties are defined as follows:

```
builder:
  type: maven2
  maven2:
    task: clean install
    system_properties:
      browser: '*firefox /usr/lib/iceweasel/firefox-bin'
      another_property: test
```

This results in

```
mvn -Dbrowser="*firefox /usr/lib/iceweasel/firefox-bin" -Danother_property="test" clean install
```

http://cpjolicoeur.lighthouseapp.com/projects/22299/tickets/5-possibility-to-define-system-properties-in-maven-2-builder
